# ===================== MODS CONFIG =====================
MOD_MAX=3

MOD_NAME_1=Mod bầu trời
MOD_URL_1=https://github.com/gta5s/Mods-On-GTA5S.NET/raw/refs/heads/main/GTA5VN_Graphic_FPS.rpf

MOD_NAME_2=Mod tiếng súng
MOD_URL_2=https://github.com/gta5s/Mods-On-GTA5S.NET/raw/refs/heads/main/GTA5VN_Graphic_FPS.rpf

MOD_NAME_3=Mod ... (them tiep)
MOD_URL_3=https://example.com/mods/other.rpf
